### PR TITLE
Try to fix the pixbuf problem.

### PR DESCRIPTION
**Pull request by cdepillabout**
Try to fix the pixbuf problem from #107.

### CODE REVIEW

**Comment by jtojnar** [comment]
I do not think this will help for https://github.com/NixOS/nixpkgs/issues/54278.  The issue is caused by mismatch between the gdk-pixbuf the project is linked against and the loaders picked up from `GDK_PIXBUF_MODULE_FILE` environment variable. And `wrapGAppsHook` should already take care of wrapping all executables with the correct version.

**Comment by jtojnar** [comment]
Right, you are overriding the `buildCommand` therefore the envHooks necessary for [gdk-pixbuf setup hook](https://github.com/NixOS/nixpkgs/blob/2ef7d171f087e5fd2a756bd38db23f379dd4a8cb/pkgs/development/libraries/gdk-pixbuf/setup-hook.sh#L17) will not run.

You could try to set it manually but I would just suggest to rely on the default builder. Something like

```nix
dontBuild = true;
installPhase = ''
  runHook preInstall
  mkdir -p $out/bin
  ln -sf ${env}/bin/termonad $out/bin/termonad
  runHook postInstall
'';
```

instead of the `buildCommand`.

**Comment by jtojnar** [comment]
There is also some kind of interaction between setup hooks and cross-compilation offsets making the example above no work: https://github.com/NixOS/nixpkgs/issues/56943

**Comment by cdepillabout** [comment]
@jtojnar Thanks for the info!  That is very helpful.

@craigem @romanofski I added an additional commit to this PR (0846a8f) fixing up the build as suggested by @jtojnar.  Could you try it out and see if it fixes your problem with Termonad segfaulting?

**Comment by romanofski** [comment]
Seems to be working for me. I tried c1d136b and yep, still segfaults. So 0846a8fb1504fd4efad480bd289629c22498c062 seems to do the trick. Is this a workaround until https://github.com/NixOS/nixpkgs/issues/56943 is fixed?

**Comment by jtojnar** [comment]
The `gdk_pixbuf` insertion is the workaround, the rest is normal – we do not recommend overriding builder unless you are fine with and none of the generic builder procedures and setup hooks working.

**Comment by cdepillabout** [comment]
Okay, since this seems to be working, I will go ahead and merge it in.

@romanofski Thanks for your help with trying out various things.  I'm glad we finally got this working for you.

@jtojnar Thanks for the suggestion to stop overriding the builder!

**Pull request merged**
