### PR TITLE
Change Colour to AlphaColour

### LINKED ISSUE #112: termonad colors should be AlphaColour
Termonad is using the [`colour`](http://hackage.haskell.org/package/colour) library to define things like cursor colors, terminal background colors, etc.

In particular, Termonad is using the [`Colour`](http://hackage.haskell.org/package/colour-2.3.5/docs/Data-Colour.html#t:Colour) type.

These `Colour` types are converted to an [`RGBA`](http://hackage.haskell.org/package/gi-gdk-3.0.21/docs/GI-Gdk-Structs-RGBA.html#t:RGBA) from `gi-gdk` in the following function:

https://github.com/cdepillabout/termonad/blob/3776e6392dd0a613f6b9e3ea85b85fe97815f685/src/Termonad/Config/Colour.hs#L464-L472

However, the `Colour` type doesn't actually have an associated alpha value, so we must use `1`.

It would be more correct to use the [`AlphaColour`](http://hackage.haskell.org/package/colour-2.3.5/docs/Data-Colour.html#t:AlphaColour) throughout the Termonad codebase instead of `Colour`.

This would be a relatively simple change.  You'd basically just have to change all the uses of `Colour` to `AlphaColour` in https://github.com/cdepillabout/termonad/blob/3776e6392dd0a613f6b9e3ea85b85fe97815f685/src/Termonad/Config/Colour.hs, and then fix all the type errors.

### PR DESCRIPTION
**Pull request by jecaro**
This PR fix #112

It seems that there is no direct way to get the RGB components back from an AlphaColour. So I needed to work around, which feels kind of hacky. See the comments for more informations.

Also the functions used to convert RGB components to word8 are not exposed from the Colour library. So I had to copy pieces of code from the Internal module to make sure it's going to behave in a consistent way.

### CODE REVIEW

**Comment by cdepillabout** [comment]
@jecaro @amir It looks like you guys both sent similar fixes at the same time!

Could you work together (review each other's PRs, possibly take code from each other) and decide on a single PR to submit?

**Comment by amir** [comment]
@jecaro admittedly your PR is way more sophisticated and complete, I'll concede.

**Comment by jecaro** [comment]
Wow, this is an awkward situation. Sorry @amir I didn't see your PR when I sent mine.

**Comment by cdepillabout** [comment]
Thanks for both of you working on this.  I just pushed commit 2657158 which adds some documentation and updates the examples.

**Pull request merged**
