### PR TITLE
Preferences file

### PR DESCRIPTION
**Pull request by jecaro**
This PR implements a basic preferences file #133. It basically works as described [here](https://github.com/cdepillabout/termonad/issues/133#issuecomment-548697841).
A few things about this:
- I've add a dependency to the yaml library to handle the file format.
- The `FromJSON` and `ToJSON` instances for `GI.Vte.Enums.CursorBlinkMode` are orphan. If needed I can wrap it in a newtype.

### CODE REVIEW

**Comment by cdepillabout** [comment]
@jecaro Thanks!

Give me a couple days to look over this.

**Comment by cdepillabout** [comment]
@jecaro Thanks, I finally got a chance to look this over.  It looks pretty good to me.

I made a few small changes (mostly just moving stuff around and adding a warning to the termonad.yaml file).  Could you do a review of the commits I added?

Once you sign off on this, I'll merge this in and cut a release to Hackage.

**Comment by jecaro** [comment]
Putting these functions in a separate file makes it nice and tidy. I just add a commit with minor changes in comments and documentation. Despite that it looks good to me.

**Comment by cdepillabout** [comment]
@jecaro Thanks for fixing stuff!

**Pull request merged**
