### PR TITLE
Pull out glade file for preferences

### PR DESCRIPTION
**Pull request by cdepillabout**
This PR is a continuation of #130 (which is for #82).

This pulls out the `.glade` file for the preferences dialog into an external file that is easy to edit with Glade.

Here is the updated preferences dialog:

image

### CODE REVIEW

**Comment by cdepillabout** [comment]
@jecaro This is a pretty simple change, but could you do a review of this?

Really the only two interesting commits are 47d4e17 (which makes a couple small changes to the glade file) and da2faaa (which adds tooltips).

I don't really know what I'm doing with Glade (and layouts in GTK in particular), so if there are any weird things in 47d4e17, please let me know.

I'll merge this in once you sign off on it.

**Comment by jecaro** [comment]
Looks fine to me. 

It's good that you had the `hexpand` properties. It makes resizing the window much better. Actually now you launched glade once, I think you know about it as much as I do :smile: 

I didn't know about the file-embed package. It is pretty neat. It makes editing the glade file very easy.

**Comment by cdepillabout** [comment]
@jecaro Thanks for the review :-)

**Comment by cdepillabout** [comment]
Released as termonad-2.1.0.0 on Hackage:

https://hackage.haskell.org/package/termonad-2.1.0.0

**Pull request merged**
