### PR TITLE
Add allowBold option

### PR DESCRIPTION
**Pull request by zanculmarktum**
Title.

### CODE REVIEW

**Comment by cdepillabout** [comment]
Thanks!

Could you give a quick explanation of why you wanted this?  I'm guessing you specifically want to disallow the terminal from using bold?

**Comment by zanculmarktum** [comment]
Yeah, basically that :^)

**Comment by cdepillabout** [comment]
@zanculmarktum Is there some reason you want to disallow the terminal from using bold?

I had wanted to write some informative haddocks, and I wanted to give a reason why people would consider setting `allowBold` to false.  Is it just personal preference?  You prefer not to see bolded characters?

**Comment by zanculmarktum** [comment]
There are some fonts that don't look quite good bold :^)

**Comment by cdepillabout** [comment]
Thanks, I added a84ed08f97e9a and merged into `master`.

**Pull request merged**
