### PR TITLE
Remove dependently-typed code

### PR DESCRIPTION
**Pull request by cdepillabout**
This supersedes #157 by @ssbothwell.  This updates that PR on the top of the current master.

### CODE REVIEW

**Comment by cdepillabout** [comment]
This looks good, but I still want to add a few more helper functions.

**Comment by ssbothwell** [comment]
What helper functions do you want? I can probably implement them.

**Comment by cdepillabout** [comment]
@ssbothwell In my personal termonad config, I have a `ColourConfig` like the following:

```haskell
let colConf =
        defaultColourConfig
          { cursorBgColour = Set $ createColour 204 0 0
          , palette =
              let myStandardColors =
                    setAtVec (fin_ (sing :: Sing N4)) (createColour 120 120 250) $
                    defaultStandardColours
                  myLightCols =
                    setAtVec (fin_ (sing :: Sing N4)) (createColour 150 150 250) $
                    defaultLightColours
              in ExtendedPalette myStandardColors myLightCols
          -- , foregroundColour = Set (createColour 220 50 50)
          -- , backgroundColour = Set (createColour 50 50 50)
          }
```

I'd like something similar to this `setAtVec` function, but for `List8`, `List24`, etc.

If you implement this, can you send it as a PR to this `ssbothwell-master` branch?

**Comment by cdepillabout** [comment]
@ssbothwell I'm going to to ahead and add this `setAtVec` function.

**Comment by cdepillabout** [comment]
@ssbothwell Thanks for working on this.

I updated this on Hackage as version 4.0.0.0: http://hackage.haskell.org/package/termonad-4.0.0.0

**Pull request merged**
