### PR TITLE
readme default compile test functional

### PR DESCRIPTION
**Pull request by Grendel-Grendel-Grendel**
#14 Figured out how to make a pull request, at least, I think I did. Here's the relevant code. I can also provide test results as proof if necessary.

### CODE REVIEW

**Comment by cdepillabout** [comment]
Hey @Grendel-Grendel-Grendel, thanks a lot for taking a look at this!  I appreciate you trying to figure out `git` and Github just to send this PR!

Unfortunately there is one or two things missing with PR.

When I try to run `stack test` on this branch, I get the following error:

```sh
$ stack test
termonad-0.2.1.0: configure (lib + exe + test)
Configuring termonad-0.2.1.0...
Warning: Packages using 'cabal-version: >= 1.10' must specify the
'default-language' field for each component (e.g. Haskell98 or Haskell2010).
If a component uses different languages in different modules then list the
other ones in the 'other-languages' field.
termonad-0.2.1.0: build (lib + exe + test)
Preprocessing library for termonad-0.2.1.0..
Building library for termonad-0.2.1.0..
ignoring (possibly broken) abi-depends field for packages
Preprocessing test suite 'termonad-test' for termonad-0.2.1.0..
Building test suite 'termonad-test' for termonad-0.2.1.0..
Preprocessing executable 'termonad' for termonad-0.2.1.0..
Building executable 'termonad' for termonad-0.2.1.0..
Preprocessing test suite 'doctests' for termonad-0.2.1.0..
Building test suite 'doctests' for termonad-0.2.1.0..
[1 of 2] Compiling Build_doctests   ( .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/doctests/autogen/Build_doctests.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/doctests/doctests-tmp/Build_doctests.o )
Linking .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/doctests/doctests ...
setup: can't find source for README in
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/readme/readme-tmp, test
            
Preprocessing test suite 'readme' for termonad-0.2.1.0..
Progress 1/2

--  While building custom Setup.hs for package termonad-0.2.1.0 using:
      /home/illabout/git/termonad/.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-2.2.0.1 build lib:termonad exe:termonad test:doctests test:readme test:termonad-test --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

Near the end of the output you can see the following lines:

```sh
...
setup: can't find source for README in
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/readme/readme-tmp, test
            
Preprocessing test suite 'readme' for termonad-0.2.1.0..
...
```

Let me try to explain what is going on here, and how it can be fixed.

You've added a `test` section to the cabal file that looks like this:

```cabal
test-suite readme
  type:           exitcode-stdio-1.0
  main-is:        README.lhs
  hs-source-dirs: test
  build-depends:  base
                  , markdown-unlit
                  , termonad
                  , colour
  ghc-options: -pgmL markdown-unlit
```

This means that when running `stack test`, stack will try to look for the file called `README.lhs` in the `test/` directory.  It will then run the program `markdown-unlit` over it to produce an actual Haskell file.

However, currently there is no file called `README.lhs` in the `test/` directory.  That's why `stack` is giving this error.

Here's how this can be fixed:

1. Add a directory within `test/` called `readme`:

    ```sh
    $ mkdir test/readme
    ```

1.  Make a soft link from `test/readme/README.lhs` to `README.md`.

    ```sh
    $ cd test/readme/
    $ ln -sf ../../README.md README.lhs
    ```
    You can also now check to make sure the link is correct:
    ```sh
    $ ls -l
    total 0
    lrwxrwxrwx 1 youruser youruser   15 Sep  2 13:26 README.lhs -> ../../README.md
    ```

1.  In the `termonad.cabal` file, you will probably have to change the `hs-source-dirs` setting from `test` to `test/readme`.

Now, when you run `stack test`, it should run successfully.  (It might actually cause a new Termonad window to open up, but we can ignore this for now.)

**Comment by Grendel-Grendel-Grendel** [comment]
My bad. Believe it or not, I had done this (except the files were just in the base test directory rather than a subdirectory) but accidentally deleted the relevant files when I was cleaning up. When I originally tested it with a correct arrangement of files it all worked, and as you said a terminal opened p. It should be fixed now. Thanks for the detailed explanation. I will look around at some other issues and try to contribute where I can.

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel thanks for cleaning it up!  I'll go ahead and merge it in!

**Comment by cdepillabout** [comment]
In commit beeebe0 I changed the README test to be an executable.  This is so that `termonad` doesn't start every time you run `stack test`.

Instead, you can now compile the executable by providing the `buildreadme` flag:

```sh
$ stack build --flag termonad:buildreadme
```

This should be added to CI (#9).

**Pull request merged**
