### PR TITLE
Options for setting font size in device units and turning off the confirm-on-exit dialog

### PR DESCRIPTION
**Pull request by LSLeary**
This should probably be two (or three) PRs in principle, but I can't really be bothered splitting the work out into separate branches right now; more importantly it's well separated into its own commits.

I don't really understand the code base yet, so if any of this should have been implemented differently, let me know and I can make changes—what matters is getting the functionality.

### CODE REVIEW

**Comment by cdepillabout** [comment]
This is great, thanks a lot!

**Comment by cdepillabout** [comment]
@LSLeary just to make sure, even if you set the `confirmExit` option to `False`, you will still be asked if you meant to close the tab when trying to close an individual tab.  This will happen when pressing the `X` for the individual tab.

Is this correct?  Or did you mean to set it up so that it doesn't ask in this case either?

**Comment by LSLeary** [comment]
Ah, I missed that. I'm not planning on using termonad tabs myself, but for the sake of completeness/correctness I can fix it up. At the moment I'm looking into fixing the recompilaton on NixOS (which currently I have reimplemented crudely in my config itself), but after that I'll have a go at it.

**Comment by cdepillabout** [comment]
> I'm not planning on using termonad tabs myself, but for the sake of completeness/correctness I can fix it up

If you could get to that, it would be great!

**Pull request merged**
