### PR TITLE
Update README.md and remove irc #termonad badge

### PR DESCRIPTION
**Pull request by cdepillabout**
I don't hang out on the #termonad room on IRC, so I don't want users to think that they could get help directly from me there.

However, if there is someone that wants to officially take over helping using on the freenode #termonad room, I'd be happy to start directing people there as well.  (Although I should probably add a section to the readme about where to get help.)

### CODE REVIEW

**Comment by craigem** [comment]
Is the IRC room being abandoned?

**Comment by cdepillabout** [comment]
@craigem I wasn't the one who created the #termonad room and I never use it.  Do you happen to know who the admin is there?

If you often hang out there and are willing to step in as the official admin (I'm not sure how this process works for IRC rooms), I'd be happy to leave a reference to the room in the README.md.

However, if no one is "officially" in charge of helping users there, I don't want people to mistakenly think they can get support there.  I'd rather people open GitHub issues if they are having problems, since I will definitely see them.

**Comment by cdepillabout** [comment]
I'm going to go ahead and merge this in, but again if anyone wants to step in and maintain the IRC room, please feel free to send a PR re-adding this badge.

**Comment by craigem** [comment]
Apologies for being a bit late on the follow up - thank you for the clarification @cdepillabout 

For the record, the traffic in that room is mostly tumbleweeds and the odd person who drops in and asks a question but leaves before anyone has time to respond.

Now there's [Matrix / Gitter interoperability](https://matrix.org/blog/2020/09/30/welcoming-gitter-to-matrix), I'll be leaving the IRC room and connecting to the Gitter room.

**Pull request merged**
